#!/usr/bin/env bash
# Spin up a local Anvil mainnet fork, deploy ArtificialBids, seed demo bids, and write
# web/.env.local so the frontend points at the fresh deployment. Idempotent: safe to re-run.
#
# Usage: MAINNET_RPC_URL=https://... ./scripts/dev-fork.sh
set -euo pipefail

RPC_LOCAL="http://127.0.0.1:8545"
FORK_RPC="${MAINNET_RPC_URL:-https://ethereum-rpc.publicnode.com}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Well-known public Anvil dev accounts (NOT secrets — local test only).
ACCT0=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266   # seller + feeRecipient + admin
ACCT0_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ACCT1=0x70997970C51812dc3A010C7d01b50e0d17dc79C8   # bidder
ACCT1_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

PIECE=0xbDF5A7F5e5AE18eE580139297C63a89fc1d18B5f
WETH=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

echo "==> (re)starting anvil fork of $FORK_RPC"
pkill -f "anvil --fork-url" 2>/dev/null || true
sleep 1
nohup anvil --fork-url "$FORK_RPC" --host 127.0.0.1 --port 8545 --chain-id 31337 --hardfork prague --silent \
  > /tmp/anvil.log 2>&1 &
for i in $(seq 1 40); do
  if cast block-number --rpc-url "$RPC_LOCAL" >/dev/null 2>&1; then break; fi
  sleep 1
done
echo "    anvil up at block $(cast block-number --rpc-url "$RPC_LOCAL")"

echo "==> deploying ArtificialBids"
cd "$ROOT/contracts"
forge script script/Deploy.s.sol --rpc-url "$RPC_LOCAL" --broadcast --private-key "$ACCT0_KEY" >/dev/null 2>&1
BIDS=$(python3 -c "import json;d=json.load(open('broadcast/Deploy.s.sol/31337/run-latest.json'));print(next(t['contractAddress'] for t in d['transactions'] if t.get('contractName')=='AAAbids'))")
DEPLOY_BLOCK=$(python3 -c "import json;d=json.load(open('broadcast/Deploy.s.sol/31337/run-latest.json'));bn=d['receipts'][0]['blockNumber'];print(int(bn,16) if isinstance(bn,str) else bn)")
echo "    AAAbids @ $BIDS (block $DEPLOY_BLOCK)"

# Batcher: EIP-7702 delegate used by the demo wallet for atomic list+accept.
BATCHER=$(forge create src/Batcher.sol:Batcher --rpc-url "$RPC_LOCAL" --private-key "$ACCT0_KEY" --broadcast 2>&1 | grep -oE 'Deployed to: 0x[0-9a-fA-F]{40}' | grep -oE '0x[0-9a-fA-F]{40}')
echo "    Batcher @ $BATCHER"

echo "==> seeding demo state"
# Give the demo seller (acct0) a few real pieces so "Your collection" is populated.
PIECE2=0x95c5a726059A533A35C9ceB53057685dfC2Eb8cb # #2
PIECE3=0x8c5053bF0526b5dcb74245f2039D9Ecc0e03c3Bf # #3
for P in $PIECE $PIECE2 $PIECE3; do
  OWNER=$(cast call $P "owner()(address)" --rpc-url "$RPC_LOCAL")
  cast rpc anvil_setBalance "$OWNER" 0xDE0B6B3A7640000 --rpc-url "$RPC_LOCAL" >/dev/null
  cast rpc anvil_impersonateAccount "$OWNER" --rpc-url "$RPC_LOCAL" >/dev/null
  cast send $P "transferOwnership(address)" $ACCT0 --from "$OWNER" --unlocked --rpc-url "$RPC_LOCAL" >/dev/null
  cast rpc anvil_stopImpersonatingAccount "$OWNER" --rpc-url "$RPC_LOCAL" >/dev/null
done

cast rpc anvil_setBalance $ACCT1 0x21E19E0C9BAB2400000 --rpc-url "$RPC_LOCAL" >/dev/null
cast send $WETH "deposit()" --value 5ether --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
cast send $WETH "approve(address,uint256)" $BIDS "$(cast max-uint)" --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
# A specific-piece bid (qty must be 1) and a collection-wide bid for 3 pieces.
cast send $BIDS "createOffer(address,uint256,uint32,uint64)" $PIECE 1ether 1 0 --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
cast send $BIDS "createOffer(address,uint256,uint32,uint64)" 0x0000000000000000000000000000000000000000 2ether 3 0 --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null

echo "==> writing web/.env.local"
cat > "$ROOT/web/.env.local" <<EOF
# Generated by scripts/dev-fork.sh — local Anvil mainnet-fork demo.
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_CHAIN_NAME=Mainnet Fork
NEXT_PUBLIC_RPC_URL=$RPC_LOCAL
NEXT_PUBLIC_BIDS_ADDRESS=$BIDS
NEXT_PUBLIC_GENESIS_ADDRESS=0xa7a3022249415e25752C4cF8696c2418DEfdF2Db
NEXT_PUBLIC_WETH_ADDRESS=$WETH
NEXT_PUBLIC_DEPLOY_BLOCK=$DEPLOY_BLOCK
NEXT_PUBLIC_DEMO_PIECE=$PIECE
NEXT_PUBLIC_DEMO_ACCOUNTS=Seller:$ACCT0,Bidder:$ACCT1
NEXT_PUBLIC_BATCHER=$BATCHER
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=
EOF

echo "==> done. Bids=$BIDS  block=$DEPLOY_BLOCK"