#!/usr/bin/env bash
# Deploy AAAbids + Batcher to an ALREADY-RUNNING local Anvil fork, seed demo bids, and write
# web/.env.local. Separate from starting anvil so the node can stay up independently.
set -euo pipefail

RPC_LOCAL="http://127.0.0.1:8545"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

ACCT0=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
ACCT0_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ACCT1=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
ACCT1_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
PIECE=0xbDF5A7F5e5AE18eE580139297C63a89fc1d18B5f
WETH=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

cd "$ROOT/contracts"
for i in $(seq 1 30); do cast block-number --rpc-url "$RPC_LOCAL" >/dev/null 2>&1 && break; sleep 1; done
echo "==> anvil at block $(cast block-number --rpc-url "$RPC_LOCAL")"

echo "==> deploy AAAbids"
forge script script/Deploy.s.sol --rpc-url "$RPC_LOCAL" --broadcast --private-key "$ACCT0_KEY" >/dev/null 2>&1
BIDS=$(python3 -c "import json;d=json.load(open('broadcast/Deploy.s.sol/31337/run-latest.json'));print(next(t['contractAddress'] for t in d['transactions'] if t.get('contractName')=='AAAbids'))")
DEPLOY_BLOCK=$(python3 -c "import json;d=json.load(open('broadcast/Deploy.s.sol/31337/run-latest.json'));bn=d['receipts'][0]['blockNumber'];print(int(bn,16) if isinstance(bn,str) else bn)")
echo "    AAAbids @ $BIDS (block $DEPLOY_BLOCK)"

echo "==> deploy Batcher"
BATCHER=$(forge create src/Batcher.sol:Batcher --rpc-url "$RPC_LOCAL" --private-key "$ACCT0_KEY" --broadcast 2>&1 | grep -oE 'Deployed to: 0x[0-9a-fA-F]{40}' | grep -oE '0x[0-9a-fA-F]{40}')
echo "    Batcher @ $BATCHER"

echo "==> seed demo state"
OWNER=$(cast call $PIECE "owner()(address)" --rpc-url "$RPC_LOCAL")
cast rpc anvil_setBalance "$OWNER" 0xDE0B6B3A7640000 --rpc-url "$RPC_LOCAL" >/dev/null
cast rpc anvil_impersonateAccount "$OWNER" --rpc-url "$RPC_LOCAL" >/dev/null
cast send $PIECE "transferOwnership(address)" $ACCT0 --from "$OWNER" --unlocked --rpc-url "$RPC_LOCAL" >/dev/null
cast rpc anvil_stopImpersonatingAccount "$OWNER" --rpc-url "$RPC_LOCAL" >/dev/null
# Give the seller a couple more pieces (#2, #3) so "Your collection" shows multiple.
for P in 0x95c5a726059A533A35C9ceB53057685dfC2Eb8cb 0x8c5053bF0526b5dcb74245f2039D9Ecc0e03c3Bf; do
  O=$(cast call $P "owner()(address)" --rpc-url "$RPC_LOCAL")
  cast rpc anvil_setBalance "$O" 0xDE0B6B3A7640000 --rpc-url "$RPC_LOCAL" >/dev/null
  cast rpc anvil_impersonateAccount "$O" --rpc-url "$RPC_LOCAL" >/dev/null
  cast send $P "transferOwnership(address)" $ACCT0 --from "$O" --unlocked --rpc-url "$RPC_LOCAL" >/dev/null
  cast rpc anvil_stopImpersonatingAccount "$O" --rpc-url "$RPC_LOCAL" >/dev/null
done

cast rpc anvil_setBalance $ACCT1 0x21E19E0C9BAB2400000 --rpc-url "$RPC_LOCAL" >/dev/null
cast send $WETH "deposit()" --value 8ether --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
cast send $WETH "approve(address,uint256)" $BIDS "$(cast max-uint)" --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
cast send $BIDS "createOffer(address,uint256,uint32,uint64)" $PIECE 1ether 1 0 --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null
cast send $BIDS "createOffer(address,uint256,uint32,uint64)" 0x0000000000000000000000000000000000000000 2ether 3 0 --private-key $ACCT1_KEY --rpc-url "$RPC_LOCAL" >/dev/null

cat > "$ROOT/web/.env.local" <<EOF
# Generated by scripts/dev-seed.sh — local Anvil mainnet-fork demo.
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_CHAIN_NAME=Mainnet Fork
NEXT_PUBLIC_RPC_URL=$RPC_LOCAL
NEXT_PUBLIC_BIDS_ADDRESS=$BIDS
NEXT_PUBLIC_GENESIS_ADDRESS=0xa7a3022249415e25752C4cF8696c2418DEfdF2Db
NEXT_PUBLIC_WETH_ADDRESS=$WETH
NEXT_PUBLIC_DEPLOY_BLOCK=$DEPLOY_BLOCK
NEXT_PUBLIC_DEMO_PIECE=$PIECE
NEXT_PUBLIC_DEMO_ACCOUNTS=Seller:$ACCT0,Bidder:$ACCT1
NEXT_PUBLIC_BATCHER=$BATCHER
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${WC_PROJECT_ID:-c9f81d63e653f2ea99c2207807303c0d}
EOF
echo "==> done. BIDS=$BIDS BATCHER=$BATCHER block=$DEPLOY_BLOCK"